### ISSUE TITLE
[BUG] Didn't update sign's text when clicking on "Done" button.

### ISSUE THREAD

**Issue by steven11304** [mrfdev/CMI#44]
I am a server owner and I have all permission nodes and the sign is working(will update sign's text when clicking on "Done" button.")
but all my players wont update sign's text when clicking on "Done" button."
 

**To Reproduce**
1.place the sign to the ground
2.write somthing
3. Click Done Buttom

**Expected behavior**
 when any of the player click Done buttom will update the sign text

**Desktop or Server**
 - OS (and version): 
 Ubuntu 22.04.2 LTS
 CMI 9.6.0.4 CMIlib 1.3.0.3
 git-Paper-30 (MC: 1.20.1)

**Comment by mrfloris** [comment]
This is my personal CMI repo, and for my server and my content, not the zrips cmi repo where you can post issues with the cmi plugin. 
https://github.com/Zrips/CMI/issues
