### ISSUE TITLE
[FEATURE] CMIUserBalanceChangeEvent.java

### ISSUE THREAD

**Issue by vipvenom** [mrfdev/CMI#50]
please make a discordsrv alert for user balance update such as user recieiving and sending money alert

also if they get money from other source like jobs ,etc and if unknown source it displays uknown source with new and old balance amount

**Comment by mrfloris** [comment]
Hey,

I've tried a few things but DiscordSRV is spitting out errors on everything I try. Not sure I can figure this one out.

**Comment by vipvenom** [comment]
oh thats not great news. 
if i successfully make it , will update you :>
